OBJS := $(patsubst %.cpp, %.o, $(shell find src -iname *.cpp))

all: clean $(OBJS) $(BIN)/$(TGT)

src/%.o:
	$(CXX) $(CXXFLAGS) -c $(patsubst %.o, %.cpp, $@) -o $(BIN)/$(shell echo $* | tr '/' '_').o

$(BIN)/$(TGT):
	$(CXX) $(CXXFLAGS) -o $(BIN)/$(TGT) $(shell find $(BIN) -iname *.o) $(LIBS)

mocks:
	find include -iname *.hpp | xargs -i% $(EXTERNALS)/gmockgen/gmock.py -c test/config/gmock.conf -l game -d test/mocks % -- $(CXXFLAGS)

clean:
	rm -f $(BIN)/*.o $(BIN)/$(TGT) $(TEST)

