.PHONY: run

BIN             := bin/linux
TGT 			:= game
TEST            := game_ut
CXX             := g++
LIBS            := -Lbin/linux -lSDL2 -lSDL2_image -lSDL2_ttf-2.0 -lfreetype
FIND 			:= find
RM 				:= rm
TR 				:= tr

include Makefile.aux

run:
	cd $(BIN) && ./$(TGT)

