.PHONY: run externals

BIN  		:= bin/linux
TGT   		:= match3
CXX   		:= g++
LD_FLAGS  	:= -Lbin/linux -lSDL2 -lSDL2_image -lSDL2_ttf-2.0 -lfreetype
FIND  		:= find
RM 	  		:= rm
TR 	  		:= tr

include Makefile.aux

run:
	cd $(BIN) && ./$(TGT)

externals:
	

