/*
 * file generated by gmock: iclient_mock.hpp
 */
#ifndef ICLIENT_MOCK_HPP
#define ICLIENT_MOCK_HPP

#include <gmock/gmock.h>
#include "iclient.hpp"

namespace match3 {
namespace mocks {

class iclient_mock : public iclient
{
public:
    virtual ~iclient_mock() { }
    MOCK_METHOD0(run, void());
};

} // namespace mocks
} // namespace match3

#endif // ICLIENT_MOCK_HPP

