/*
 * file generated by gmock: ipoints_mock.hpp
 */
#ifndef IPOINTS_MOCK_HPP
#define IPOINTS_MOCK_HPP

#include <gmock/gmock.h>
#include "ipoints.hpp"

namespace game {
namespace mocks {

class ipoints_mock : public ipoints
{
public:
    virtual ~ipoints_mock() { }
    MOCK_METHOD1(add, void(int));
    MOCK_METHOD1(sub, void(int));
    virtual operator int() const override { return 0; }
};

} // namespace mocks
} // namespace game

#endif // IPOINTS_MOCK_HPP

