/*
 * file generated by gmock: irandom_mock.hpp
 */
#ifndef IRANDOM_MOCK_HPP
#define IRANDOM_MOCK_HPP

#include <gmock/gmock.h>
#include "irandom.hpp"

namespace game {

class irandom_mock : public irandom
{
public:
    virtual ~irandom_mock();

    MOCK_CONST_METHOD2(get_random_number, int(int, int));
};

} // namespace game

#endif // IRANDOM_MOCK_HPP

