/*
 * file generated by gmock: isdl_mock.hpp
 */
#ifndef ISDL_MOCK_HPP
#define ISDL_MOCK_HPP

#include <gmock/gmock.h>
#include "isdl.hpp"

namespace game {
namespace gui {

class isdl_mock : public isdl
{
public:
    virtual ~isdl_mock();

    MOCK_CONST_METHOD1(load_image, boost::shared_ptr<SDL_Surface>(const std::string &));
    MOCK_METHOD3(apply_surface, void(boost::shared_ptr<SDL_Surface>, int, int));
    MOCK_METHOD0(refresh, void());
};

} // namespace game
} // namespace gui

#endif // ISDL_MOCK_HPP

