/*
 * file generated by gmock: iviewer_mock.hpp
 */
#ifndef IVIEWER_MOCK_HPP
#define IVIEWER_MOCK_HPP

#include <gmock/gmock.h>
#include "iviewer.hpp"

namespace game {

class iviewer_mock : public iviewer
{
public:
    virtual ~iviewer_mock();

    MOCK_METHOD0(init, void());
    MOCK_METHOD0(refresh, void());
    MOCK_METHOD2(show_grid, void(const detail::position &, detail::color_t));
    MOCK_METHOD1(show_match, void(const detail::position &));
    MOCK_METHOD1(select_item, void(const detail::position &));
};

} // namespace game

#endif // IVIEWER_MOCK_HPP

