/*
 * file generated by gmock: iwindow_mock.hpp
 */
#ifndef IWINDOW_MOCK_HPP
#define IWINDOW_MOCK_HPP

#include <gmock/gmock.h>
#include "iwindow.hpp"

namespace game {
namespace gui {

class iwindow_mock : public iwindow
{
public:
    virtual ~iwindow_mock();

    MOCK_METHOD0(clear, void());
    MOCK_METHOD0(render, void());
    MOCK_METHOD0(quit, void());
};

} // namespace game
} // namespace gui

#endif // IWINDOW_MOCK_HPP

